M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu24.04.1} date 2024-10-10T17:44:52+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-10T17:44:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X3.9906Y-1.5343
X4.2181Y-1.5343
M30
